version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: ml_api/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./ml_api:/app/ml_api
      - ./ml_api/data:/app/ml_api/data

  web:
    build:
      context: .
      dockerfile: web_dash/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - API_URL=http://api:5000
    depends_on:
      - api
